### PR TITLE
add DE+EN descriptions to fastlane

### PR DESCRIPTION
**Pull request by IzzySoft**
For your MR with F-Droid :wink:

### CODE REVIEW

**Comment by adolfintel** [comment]
Thanks. I'll update the MR asap

**Comment by IzzySoft** [comment]
Don't forget this needs to be tagged before it becomes valid for your MR (F-Droid looks for Fastlane at the same tag/commit it builds the app from).

**Comment by adolfintel** [comment]
Yeah, I forgot. I recreated the 1.0 tag

**Comment by IzzySoft** [comment]
Yepp, thanks – all fine now! I'm just afraid it will take a while until the MR is processed further. I went on a triage run at fdroiddata yesterday, and am shocked to see how much is stalled there – most of it not waiting for upstream or the reporter, but for our packagers :scream: They're not lazy, don't get this wrong – they are far too few…

**Comment by adolfintel** [comment]
You know, I've been using F-Droid for ages and I'm a fairly competent developer, can I apply to help you out with those MRs?

**Comment by IzzySoft** [comment]
That would be phantastic! Could you check the MRs [marked for review](https://gitlab.com/fdroid/fdroiddata/-/merge_requests?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=review-requested) and see if the code is fine/builds – then leave a corresponding comment? Once you've processed a few (say 2-3) let me know the MR numbers so I can use them as reference. I'll then request your "initiation" as a project member, so you get some elevated privileges helping you doing that even easier/better.

Thanks a lot!

**Comment by adolfintel** [comment]
Can you write me at info@fdossena.com? I need to ask you a couple questions about how you test app submissions

**Pull request merged**
